### PR TITLE
Characters  / fonts

### PR DESCRIPTION
**Pull request by PJBrs**
Hi @matsavage ,

You asked whether I could provide some example characters, please find them in this PR. Let me know if this is what you're looking for.

Also, I was pondering the whole "kalam font is not in my path", and I wrote a patch to be a bit more resilient about that. I also noticed that some latex packages on ctan do package a font, but they (automatically?) add it to the texmf font directory. Perhaps that could be an inspiration? See here: https://github.com/rallg/novel

And I have a question; I recently switched to using lualatex to compile characters with your template. It needs luapstricks and requires adding `\DocumentMetadata{}` to your latex file, but other than that, it compiles very nicely (requires 2 passes), and it doesn't need tweaking dvipdfmx.cfg . I'm on Slackware-15.0, not the most bleeding edge distro, and luapstricks is part of the standard texlive package.

### CODE REVIEW

**Comment by PJBrs** [comment]
Don't know why the checks fail... In the meantime, I just noticed that finding the font works with this:
`TTFONTS=.:$(kpsewhich dndtemplate.sty | sed s/dndtemplate.sty//): lualatex $charfile.tex`

**Comment by PJBrs** [comment]
... In fact, I just succeeded in adding your template to dungeonsheets as a submodule :-) So maybe that font patch is redundant anyway.

**Comment by matsavage** [comment]
Thanks, these look great, and thanks for the dungeon-sheets integrations work.

I've updated the pipeline a bit, so that error logs can be seen, however, github seems to be cutting out the bottom bit.

Running locally, I can see that the issue is that the font can't be found when running in nix, this font inclusion really has been a pain for the whole thing, and was the reason I never really got the submodule thing working in dungon sheets

**Comment by PJBrs** [comment]
You're welcome! I can't code very well, and it's rather gratifying to be of use for some projects! If you want, you can check my [wishlist-pj tree](https://github.com/PJBrs/dungeon-sheets/tree/wishlist-pj), which includes the submodule patch. I added your template to one of the tests as well, and they all pass the github workflow. [This commit](https://github.com/canismarko/dungeon-sheets/commit/c91829e9a62b8cfc6a9d8a09be8d874e7efc74bd) (until I rebase and force push, that is). By the way, I'm doing this without docker or nix, and I don't really understand how they work, but I do think that your nix build would also succeed if you set the TTFONTS variable in your environment. In the tests on github it shows as follows:
`DEBUG:dungeonsheets.latex:LaTeX command: lualatex --output-directory /home/runner/work/dungeon-sheets/dungeon-sheets/examples -halt-on-error -interaction=nonstopmode sorcerer1_char.tex`
[snip]
```
DEBUG:dungeonsheets.latex:    TEXINPUTS: .:/home/runner/work/dungeon-sheets/dungeon-sheets/dungeonsheets/modules/DND-5e-LaTeX-Template:/home/runner/work/dungeon-sheets/dungeon-sheets/dungeonsheets/modules/DND-5e-LaTeX-Character-Sheet-Template:/home/runner/work/dungeon-sheets/dungeon-sheets/dungeonsheets/modules:
10949
DEBUG:dungeonsheets.latex:    TTFONTS: .:/home/runner/work/dungeon-sheets/dungeon-sheets/dungeonsheets/modules/DND-5e-LaTeX-Template:/home/runner/work/dungeon-sheets/dungeon-sheets/dungeonsheets/modules/DND-5e-LaTeX-Character-Sheet-Template:/home/runner/work/dungeon-sheets/dungeon-sheets/dungeonsheets/modules:
```
By the way, I noticed that some of the images of compiled characters in your repo actually don't have transparancies, might want to check that :-)

**Comment by matsavage** [comment]
Having looked into lualatex and the document metadata, which version on LaTeX are you running on?

The version in the nix flake is: 
```
mathew@...:~/repos/DND-LaTeX/DND-5e-LaTeX-Character-Sheet-Template$ latex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01


mathew@...:~/repos/DND-LaTeX/DND-5e-LaTeX-Character-Sheet-Template$ lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)

Execute  'luatex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2019 Taco Hoekwater and the LuaTeX Team.
```

At this time I'm hesitant to update anything to do with this, as I don't really know the system all that well, is it possible to make these sheets the older way?

**Comment by PJBrs** [comment]
```
$ lualatex --version
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023 on Slackware)
$xelatex --version
XeTeX 3.141592653-2.6-0.999995 (TeX Live 2023 on Slackware)
```
What I noticed with the github workflow is that I needed to explicitly needed to load a package. So the first lines actually should have been:
```
\RequirePackage{pdfmanagement-testphase}
\DocumentMetadata{}
```
Newer versions of latex automatically load pdfmanagement-testphase if \DocumentMetadata{} is in the file, older ones need to have it added specifically. I think that the workflow over at github uses texlive2021 (if I understand the logs correctly). Obviously, I can't see the result, but it compiles without error. Oh, and it needs texlive-pstricks added to the dependencies to compile in the github testing workflow.

Locally, I removed the -DNOSAFER bit from xdvipdfmx.cfg, so now I don't have transparencies anymore with xelatex, but lualatex actually compiles fine, and faster.

**Comment by PJBrs** [comment]
OK, I tried a bit but didn't succeed. With xelatex, it reports that the font can't be found, and I'm unable to change your flake.nix to get lualatex in there.

**Comment by matsavage** [comment]
I had a look at the changes this morning, and there were a couple of missing packages needed for lualatex, but I feel the font is still what's causing the issue.

At this point I have to ask what is the benefit of moving to lualatex, everything worked fine before, and this is likely to break the compatibility of anyone else using the project.

Surely the characters will work without the other features

**Comment by PJBrs** [comment]
Ah, you're quite right, on this nixos environment, the lualatex build apparently fails on the pstricks files. I think it succeeded withouth the bits of:
```
\RequirePackage{pdfmanagement-testphase}
\DocumentMetadata{}
```
... in the latex files, but then the results failed the test phase in your workflow, probably because of missing transparencies. The xelatex build comes further now (all the test formats build fine now), and that's because I dropped that font path patch...

**Comment by matsavage** [comment]
I don't mind the test phase failing, if there have been changes to how we render the project, that's mostly there to make sure there's no unexpected changes to how the tests render caused by something else.

I'm struggling to follow this a little, any chance of a call at some point, I'm based in the UK and have a bit of time this evening.

**Comment by matsavage** [comment]
Having the fonts path definitely seems preferable to patching the `.sty` file, I think the images thing may just be a path issue, I feel `characters/image/image.jpg` will probably work.

I would recommend installing nix, and trying to debug locally rather than pushing to the branch over and over and waiting for the actions, as it'll be much faster and less frustrating. The ideal situation would be that the project `Just Works` with local installs and inside nix

There's an email on my profile page, feel free to drop an invite for google meet/zoom whatever over there, or I'm @mathewsavage on discord

**Comment by matsavage** [comment]
I've had a bit more of a look at this, and I feel like lualatex is working fine, and this is the issue we're coming up against: https://tex.stackexchange.com/questions/34242/why-does-lualatex-return-with-exit-code-1-even-though-a-pdf-was-built

When I go into the nix shell and run the command myself, a perfectly fine PDF is generated, I am also surprised by how quick it is.

**Comment by matsavage** [comment]
I have raised a PR here, but the backgrounds aren't transparent for some reason, you said you had a fix for this?

https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/pull/72

**Comment by PJBrs** [comment]
Hi @matsavage any comment on this PR? As far as I can tell, it just does what it's supposed to be doing, in the sense that:

- Lualatex "just works" (https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/pull/65/commits/d862e2577aa0445f56231d6dc8d0483ff09bf003)
- ... because I changed the test a bit and because ... (https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/pull/65/commits/63a9b0e6512b0475963315cf71a75e899dffe543)
- It works around the case where pstricks transparency isn't availeble (https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/pull/65/commits/d711b6c7b38007613aec3a88c25629dc2384806a)

... and you get some example characters on the side :-)

**Review by matsavage — APPROVED** [review]

**Comment by matsavage** [comment]
Approved, thanks so much for pushing through the work on this, I know it has been a lot, but it looks like we're really in a very good place now.

**Pull request merged**
