### PR TITLE
47 half caster spell sheet

### PR DESCRIPTION
**Pull request by matsavage**
Adds half caster spell sheet

Thanks for the help @PJBrs, it's really come together.

### CODE REVIEW

**Comment by PJBrs** [comment]
@matsavage  Very cool! Thanks very much!

In the meantime, I'm still hacking away on some remaining bits to prepare my dungeonsheets pull. Please don't test yet, I just noticed that I could replace a couple of very ugly hacks to remove whitespace and indents with nice clean jinja code that I didn't know about.

**Comment by PJBrs** [comment]
@matsavage I made some final final final changes to my branch over here:

https://github.com/PJBrs/dungeon-sheets/tree/MSavage-latex-template

It still has the same output, but the code is cleaner. Please let me know if you can test this a bit. On my end, I compiled all example sheets with:

`for i in *py *json; do makesheets -TF $i; done`

and everything compiles fine.  I'd like your experiences before I raise the PR with dungeonsheets.

**Comment by matsavage** [comment]
In all honesty I’ve not used dungeon sheets a lot. Any review would just be from a python pov, I made this project with the aim of using it but ended up not in the end. 

In all honesty I’ve not played DnD for 3/4 years, my play group moved to pathfinder 2e.

I’ve had a busy day adding tests to compare a current build of the sheets vs a known PDF: https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/pull/59

I’ve used the half caster sheet as an example, I just need to make templates for the other 3, but the hard work is done. 

Would I be able to ask you for some example complete character sheets, maybe something produced by dungeon sheets once your changes have been merged.

**Comment by PJBrs** [comment]
Hi, I can certainly add some characters. Dungeonsheets already produces pretty clean latex (I assume you need latex source, not pdf :-) ). They only would not use the newest calculation features in your template, but I don't think that's necessarily a problem. 

What specifically are you looking for? Should they be real-world characters? I have a couple of those around level 4 / 5, including pictures and some backstory. I also have a couple of level 2 characters from family members, and one from myself. Most importantly - what do you need the examples to exemplify?

**Pull request merged**
